[View in Colaboratory](https://colab.research.google.com/github/Bing5154/Summer18/blob/master/2dConvolution.ipynb)

In [0]:
import numpy as np
from scipy import signal
from scipy import misc



In [2]:
x = np.array([[1,2,0], [4,1,1], [3,1,2]])
w = np.array([[2,2], [1,-1]])

print("x = \n", x)
print("\n")
print("w = \n", w)
print("\n")

res1 = signal.convolve2d(x,w,'valid')
res2 = signal.convolve2d(x,w,'same')
res3 = signal.convolve2d(x,w,'full')

print("valid convolution(x,w) = \n", res1) #valid 2d convolution
print("\n same convolution(x,w) = \n", res2) #same 2d convolution
print("\n full convolution(x,w) = \n", res3) #full 2d convolution


x = 
 [[1 2 0]
 [4 1 1]
 [3 1 2]]


w = 
 [[ 2  2]
 [ 1 -1]]


valid convolution(x,w) = 
 [[11  2]
 [ 5  6]]

 same convolution(x,w) = 
 [[ 2  6  4]
 [ 9 11  2]
 [10  5  6]]

 full convolution(x,w) = 
 [[ 2  6  4  0]
 [ 9 11  2  2]
 [10  5  6  3]
 [ 3 -2  1 -2]]


In [3]:
y = np.array([[1,0,1,-1],[1,-1,3,0],[0,1,2,-1], [1,2,0,1]])
z = np.array([[1,-1], [1,2]])

print("y = \n", y)
print("\n")
print("z = \n", z)
print("\n")

res1 = signal.convolve2d(y,z,'valid')
res2 = signal.convolve2d(y,z,'same')
res3 = signal.convolve2d(y,z,'full')

print("valid convolution(y,z) = \n", res1) #valid 2d convolution
print("\n same convolution(y,z) = \n", res2) #same 2d convolution
print("\n full convolution(y,z) = \n", res3) #full 2d convolution





y = 
 [[ 1  0  1 -1]
 [ 1 -1  3  0]
 [ 0  1  2 -1]
 [ 1  2  0  1]]


z = 
 [[ 1 -1]
 [ 1  2]]


valid convolution(y,z) = 
 [[ 0  5 -2]
 [ 2  2  3]
 [ 2  2  4]]

 same convolution(y,z) = 
 [[ 1 -1  1 -2]
 [ 2  0  5 -2]
 [ 1  2  2  3]
 [ 1  2  2  4]]

 full convolution(y,z) = 
 [[ 1 -1  1 -2  1]
 [ 2  0  5 -2 -2]
 [ 1  2  2  3  1]
 [ 1  2  2  4 -3]
 [ 1  4  4  1  2]]


In [13]:
c = np.array([[1,1,0,-1],[1,0,2,1],[3,1,0,1]])
d = np.array([[1,-1],[1,2]])

res1 = signal.convolve2d(c,d,'valid')

print(res1)

[[ 2  4 -2]
 [ 0  1  6]]


In [4]:
e = np.array([[1,0,2],[1,1,-1],[2,0,2]])
f = np.array([[1,-1],[0,2]])

print("e = \n", e)
print("\n")
print("f = \n", f)
print("\n")

res1 = signal.convolve2d(e,f,'valid')
res2 = signal.convolve2d(e,f,'same')
res3 = signal.convolve2d(e,f,'full')

print("valid convolution(e,f) = \n", res1) #valid 2d convolution
print("\n same convolution(e,f) = \n", res2) #same 2d convolution
print("\n full convolution(e,f) = \n", res3) #full 2d convolution




e = 
 [[ 1  0  2]
 [ 1  1 -1]
 [ 2  0  2]]


f = 
 [[ 1 -1]
 [ 0  2]]


valid convolution(e,f) = 
 [[ 2 -2]
 [ 0  4]]

 same convolution(e,f) = 
 [[ 1 -1  2]
 [ 1  2 -2]
 [ 2  0  4]]

 full convolution(e,f) = 
 [[ 1 -1  2 -2]
 [ 1  2 -2  5]
 [ 2  0  4 -4]
 [ 0  4  0  4]]


In [5]:
g = np.array([[1,1,2,0],[-1,0,1,1],[2,1,-1,0],[1,0,1,2]])
h = np.array([[0,2],[-1,3]])

res1 = signal.convolve2d(g,h,'valid')
print("valid convolution(g,h) = \n", res1)

valid convolution(g,h) = 
 [[ 0  1  8]
 [ 1  1  0]
 [ 7  4 -1]]
