[View in Colaboratory](https://colab.research.google.com/github/Bing5154/AI4AV/blob/master/numpy.ipynb)

In [26]:
import numpy as np

print("\n Shape and Rank")
a = np.array([1,2,3]) #create a rank of 1 array, rank = dimension
                      #[1,2,3]: 1 dimensional (rank1) array
                      #[[1,2,3]]: 2 dimensional (rank2) array
                      
                      
print(type(a))
print(a.shape) #shape = the size returns(row# x col#)
               #1 dimensional only contains the column number ex.(3,) 
               #shape depends on dimension
print(a[0],a[1],a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

print("\nConstant array")
c = np.full((2,3),1)  #first parameter size, 2nd value
print(c)
print(c.shape)

print("\n Modifying Matrix")
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2, 1:3]  #slicing array (desired row, desired col), same with list
print(a[0,1])
b[0,0] = 77    #obtaining element of matrix,similar to list but need 2 vals
print(a[0,1])  #setting element of matrix

e = np.array([3,5,1])
print(e)
print("\n")

print("\n array indexing / Mutation")
f = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(f)
print("\n")
k = np.array([0,2,0,1])
print(f[np.arange(4),k])  #row number 0-3 (not random), b as column number
print("\n")
f[np.arange(4),k] += 10 #increments chosen element by 10
print(f)

print("\nTranspose")
x = np.array([[5,10],[99,8]])
print (x)
print(x.T)

print("\nTranspose 2")
y = np.array(([[1,2,3], [4,5,6]]))
print(y)
print(y.T)







 Shape and Rank
<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4

Constant array
[[1 1 1]
 [1 1 1]]
(2, 3)

 Modifying Matrix
2
77
[3 5 1]



 array indexing
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[ 1  6  7 11]


[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]

Transpose
[[ 5 10]
 [99  8]]
[[ 5 99]
 [10  8]]

Transpose 2
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
