[View in Colaboratory](https://colab.research.google.com/github/Bing5154/Summer18/blob/master/Pytorch_Tensor.ipynb)


# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of audiences:

-  Tensorial library that uses the power of GPUs
-  A deep learning research platform that provides maximum flexibility and speed

## Import the library

In [0]:
# http://pytorch.org/
from os import path
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())

accelerator = 'cu90' if path.exists('/opt/bin/nvidia-smi') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.0-{platform}-linux_x86_64.whl torchvision
import torch  # <Ctrl> / <Shift> + <Return>

In [106]:
torch.__version__

'0.4.0'

## Getting help in Jupyter

In [107]:
torch.sqrt  # <Tab>

<function _VariableFunctions.sqrt>

In [0]:
# What about all `*Tensor`s?
torch.*Tensor?

In [109]:
torch.nn.Module()  # <Shift>+<Tab>

Module()

In [0]:
# Annotate your functions / classes!
torch.nn.Module?

In [0]:
torch.nn.Module??

## Dropping to Bash: magic!

In [112]:
! ls -lh

total 4.0K
drwxr-xr-x 3 root root 4.0K Jul 16 17:37 datalab


In [113]:
%%bash
for f in $(ls *.*); do
    echo $(wc -l $f)
done

ls: cannot access '*.*': No such file or directory


In [0]:
# Help?
%%bash?

In [0]:
# Getting some general help
%magic

## Python native data types

Python has many native datatypes. Here are the important ones:

 - **Booleans** are either `True` or `False`.
 - **Numbers** can be integers (1 and 2), floats (1.1 and 1.2), fractions (1/2 and 2/3), or even complex numbers.
 - **Strings** are sequences of Unicode characters, e.g. an html document.
 - **Lists** are ordered sequences of values.
 - **Tuples** are ordered, immutable sequences of values.
 - **Sets** are unordered bags of values.
 - **Dictionaries** are unordered bags of key-value pairs.
 
See [here](http://www.diveintopython3.net/native-datatypes.html) for a complete overview.

### More resources

 1. Brief Python introduction [here](https://learnxinyminutes.com/docs/python3/).
 2. Full Python tutorial [here](https://docs.python.org/3/tutorial/).
 3. A Whirlwind Tour of Python [here](https://github.com/jakevdp/WhirlwindTourOfPython).
 4. Python Data Science Handbook [here](https://github.com/jakevdp/PythonDataScienceHandbook).

## Torch!

In [116]:
t = torch.Tensor(2, 3, 4)  #create the tensor with dimension 2x3x4
type(t)
print(t)

tensor([[[ 4.5796e-36,  0.0000e+00,  7.2719e+22,  7.5044e+28],
         [ 2.8405e+20,  1.8503e+20,  8.3280e+35,  1.7830e+19],
         [ 7.0062e+22,  7.1221e+28,  7.1441e+31,  1.1259e+24]],

        [[ 7.4451e+34,  1.1704e-19,  1.3563e-19,  2.9538e+21],
         [ 7.0806e+31,  1.1626e+27,  8.7530e-04,  1.3563e-19],
         [ 1.3563e-19,  1.3563e-19,  4.4359e+27,  7.1440e+31]]])


In [117]:
t.size()  #telling you the size (row, column, height) in list

torch.Size([2, 3, 4])

In [118]:
# t.size() is a classic tuple =>
print('t size:', ' \u00D7 '.join(map(str, t.size())))

t size: 2 × 3 × 4


In [119]:
print(f'point in a {t.numel()} dimensional space')  #the total spaces, volume
print(f'organised in {t.dim()} sub-dimensions')   #how many dimensions

point in a 24 dimensional space
organised in 3 sub-dimensions


In [120]:
t

tensor([[[ 4.5796e-36,  0.0000e+00,  7.2719e+22,  7.5044e+28],
         [ 2.8405e+20,  1.8503e+20,  8.3280e+35,  1.7830e+19],
         [ 7.0062e+22,  7.1221e+28,  7.1441e+31,  1.1259e+24]],

        [[ 7.4451e+34,  1.1704e-19,  1.3563e-19,  2.9538e+21],
         [ 7.0806e+31,  1.1626e+27,  8.7530e-04,  1.3563e-19],
         [ 1.3563e-19,  1.3563e-19,  4.4359e+27,  7.1440e+31]]])

In [139]:
# Mind the underscore!
# why?
t.random_(10)

tensor([[[ 1.,  9.,  0.,  9.],
         [ 1.,  6.,  6.,  4.],
         [ 4.,  5.,  1.,  1.]],

        [[ 6.,  6.,  8.,  3.],
         [ 7.,  2.,  8.,  5.],
         [ 9.,  9.,  3.,  8.]]])

In [121]:
t  # more brief way to print out the tensor

tensor([[[ 4.5796e-36,  0.0000e+00,  7.2719e+22,  7.5044e+28],
         [ 2.8405e+20,  1.8503e+20,  8.3280e+35,  1.7830e+19],
         [ 7.0062e+22,  7.1221e+28,  7.1441e+31,  1.1259e+24]],

        [[ 7.4451e+34,  1.1704e-19,  1.3563e-19,  2.9538e+21],
         [ 7.0806e+31,  1.1626e+27,  8.7530e-04,  1.3563e-19],
         [ 1.3563e-19,  1.3563e-19,  4.4359e+27,  7.1440e+31]]])

In [122]:
r = torch.Tensor(t) #similar to int() in numpy, 
                    #converting t into tensor and call it r
                    #parameter can also contain dimensions
                    #now they are alias to each other
r.resize_(3, 8)
r

tensor([[ 4.5796e-36,  0.0000e+00,  7.2719e+22,  7.5044e+28,  2.8405e+20,
          1.8503e+20,  8.3280e+35,  1.7830e+19],
        [ 7.0062e+22,  7.1221e+28,  7.1441e+31,  1.1259e+24,  7.4451e+34,
          1.1704e-19,  1.3563e-19,  2.9538e+21],
        [ 7.0806e+31,  1.1626e+27,  8.7530e-04,  1.3563e-19,  1.3563e-19,
          1.3563e-19,  4.4359e+27,  7.1440e+31]])

In [123]:
r.zero_()  #set everything to zero, remember underscore

tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [140]:
t # how did t change value? Had the same value as r

tensor([[[ 1.,  9.,  0.,  9.],
         [ 1.,  6.,  6.,  4.],
         [ 4.,  5.,  1.,  1.]],

        [[ 6.,  6.,  8.,  3.],
         [ 7.,  2.,  8.,  5.],
         [ 9.,  9.,  3.,  8.]]])

In [0]:
# This *is* important, sigh...
s = r.clone()  #create a copy of r, 3x8

In [126]:
#all method call should have _, constant matrix
s.fill_(1)  
s

tensor([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [35]:
r

tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

## Vectors (1D Tensors)

In [41]:
#with bracket, so not dimensions but a vector
v = torch.Tensor([1, 2, 3, 4]); v  

tensor([ 1.,  2.,  3.,  4.])

In [38]:
print(f'dim: {v.dim()}, size: {v.size()[0]}') 

dim: 1, size: 4


In [39]:
w = torch.Tensor([1, 0, 2, 0]); w

tensor([ 1.,  0.,  2.,  0.])

In [40]:
# Element-wise multiplication
v * w

tensor([ 1.,  0.,  6.,  0.])

In [42]:
# Scalar product: 1*1 + 2*0 + 3*2 + 4*0
v @ w

tensor(7.)

In [79]:
#dimension of 5 with random numbers between 0 to 99
x = torch.Tensor(5).random_(100); x   

tensor([ 46.,  79.,  81.,  66.,  99.])

In [45]:
print(f'first: {x[0]}, last: {x[-1]}')  #indexing, negative works too

first: 4.0, last: 5.0


In [46]:
# Extract sub-Tensor [from:to)
x[1:2 + 1]

tensor([ 7.,  7.])

In [48]:
v

tensor([ 1.,  2.,  3.,  4.])

In [0]:
#arange: [start, end)
#to get 1 to 4, arange[1,5)
v = torch.arange(1, 4 + 1); v


 1
 2
 3
 4
[torch.FloatTensor of size 4]

In [49]:
#element wise exponent, doesn't change v
print(v.pow(2), v)

tensor([  1.,   4.,   9.,  16.]) tensor([ 1.,  2.,  3.,  4.])


In [50]:
#element wise exponet, does change v
print(v.pow_(2), v)

tensor([  1.,   4.,   9.,  16.]) tensor([  1.,   4.,   9.,  16.])


## Matrices (2D Tensors)

In [51]:
m = torch.Tensor([[2, 5, 3, 7],
                  [4, 2, 1, 9]]); m

tensor([[ 2.,  5.,  3.,  7.],
        [ 4.,  2.,  1.,  9.]])

In [52]:
m.dim()

2

In [60]:
# size(0) --> number of rows
# size(1) --> number of cols
# tensor.size() --> the size of the matrix in array
print(m.size(0), m.size(1), m.size(), sep=' -- ')

2 -- 4 -- torch.Size([2, 4])


In [0]:
#how many elements in total, 2x4
m.numel()

8

In [61]:
#indexing
m[0][2]

tensor(3.)

In [62]:
m[0, 2]

tensor(3.)

In [0]:
#slicing, shape not kept
m[:, 1]


 5
 2
[torch.FloatTensor of size 2]

In [64]:
# slicing
# if bracket added
# the shape in the sub matrix are kept
# aka. same dimension as m
m[:, [1]]

tensor([[ 5.],
        [ 2.]])

In [63]:
m[[0], :]

tensor([[ 2.,  5.,  3.,  7.]])

In [65]:
m[0, :]

tensor([ 2.,  5.,  3.,  7.])

In [66]:
# arange: [start, end)
v = torch.arange(1, 4 + 1); v

tensor([ 1.,  2.,  3.,  4.])

In [67]:
# scalar
m @ v  

tensor([ 49.,  47.])

In [68]:
# 2x1 + 5x2 + 3x3 + 7x4 = 49
m[[0], :] @ v   

tensor([ 49.])

In [69]:
# 4x1 + 2x2 + 3x1 + 9x4 = 47
m[[1], :] @ v 

tensor([ 47.])

In [70]:
# rand(m, n) creates a random 2-dimensional matrix
# add m and rand
m + torch.rand(2, 4)

tensor([[ 2.9468,  5.6908,  3.5284,  7.7318],
        [ 4.2998,  2.2113,  1.6123,  9.5629]])

In [71]:
# subtract m and rand elementwise
m - torch.rand(2, 4)

tensor([[ 1.9051,  4.9015,  2.4309,  6.1532],
        [ 3.6316,  1.7443,  0.9364,  8.9203]])

In [75]:
# multiply m and rand element wise
m * torch.rand(2, 4)

tensor([[ 0.5070,  3.4993,  0.2083,  0.8771],
        [ 0.6052,  1.2299,  0.6296,  4.9760]])

In [76]:
# divide m and rand element wise
m / torch.rand(2, 4)

tensor([[  7.6253,  18.3319,  21.7557,  11.0003],
        [  4.4909,   4.9415,   1.0994,  16.7943]])

In [77]:
# tranpose of m
m.t()

tensor([[ 2.,  4.],
        [ 5.,  2.],
        [ 3.,  1.],
        [ 7.,  9.]])

In [78]:
# Same as
m.transpose(0, 1)

tensor([[ 2.,  4.],
        [ 5.,  2.],
        [ 3.,  1.],
        [ 7.,  9.]])

## Constructors

In [83]:
torch.arange(3, 8 + 1)

tensor([ 3.,  4.,  5.,  6.,  7.,  8.])

In [84]:
# arange(start, end, step)
# step ==> intervals 
torch.arange(5.7, -3, -2.1)

tensor([ 5.7000,  3.6000,  1.5000, -0.6000, -2.7000])

In [85]:
#linspace(like arange): returns one dimensional tensor with (start,end,step)
#view: Returns a new tensor with the same data but of a set size.
torch.linspace(3, 8, 20).view(1, -1) 

tensor([[ 3.0000,  3.2632,  3.5263,  3.7895,  4.0526,  4.3158,  4.5789,
          4.8421,  5.1053,  5.3684,  5.6316,  5.8947,  6.1579,  6.4211,
          6.6842,  6.9474,  7.2105,  7.4737,  7.7368,  8.0000]])

In [87]:
torch.zeros(3, 5)  

tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])

In [88]:
torch.ones(3, 2, 5)

tensor([[[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]]])

In [100]:
# eye == identity matrix
torch.eye(3)

tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])

In [0]:
# Pretty plotting config
%run ~/Dropbox/NYU/Work/plot_conf.py

In [0]:
# Pretty plotting config
%run ~/Dropbox/NYU/Work/plot_conf.py

In [0]:
# Numpy bridge!
plt.hist(torch.randn(1000).numpy(), 100);

In [0]:
plt.hist(torch.randn(10**6).numpy(), 100);  # how much does this chart weight?
# use rasterized=True for SVG/EPS/PDF!

In [0]:
plt.hist(torch.rand(10**6).numpy(), 100);

## Casting

In [0]:
# show differnt types of tensor
torch.*Tensor?

In [102]:
m

tensor([[ 2.,  5.,  3.,  7.],
        [ 4.,  2.,  1.,  9.]])

In [103]:
# cast int to double
m.double()

tensor([[ 2.,  5.,  3.,  7.],
        [ 4.,  2.,  1.,  9.]], dtype=torch.float64)

In [129]:
# cast double to byte
m.byte()

tensor([[ 2,  5,  3,  7],
        [ 4,  2,  1,  9]], dtype=torch.uint8)

In [0]:
# checks if your package contains CUDA
# CUDA is necessary for running GPUs
# return bool
if torch.cuda.is_available():
    m.cuda()

In [132]:
# tensor to array
# what is the difference between array and tensor?
m_np = m.numpy(); m_np

array([[2., 5., 3., 7.],
       [4., 2., 1., 9.]], dtype=float32)

In [0]:
m_np[0, 0] = -1; m_np

array([[-1.,  5.,  3.,  7.],
       [ 4.,  2.,  1.,  9.]], dtype=float32)

In [0]:
m


-1  5  3  7
 4  2  1  9
[torch.FloatTensor of size 2x4]

In [134]:
# from_numpy(): cast array to tensor
import numpy as np
n_np = np.arange(5)
n = torch.from_numpy(n_np) #n is a tensor
print(n_np, n)

[0 1 2 3 4] tensor([ 0,  1,  2,  3,  4])


In [135]:
# how does changing n affects n_np
n.mul_(2)
n_np

array([0, 2, 4, 6, 8])

## More fun

In [136]:
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])
print(a, b)

tensor([[ 1.,  2.,  3.,  4.]]) tensor([[ 5.,  6.,  7.,  8.]])


In [137]:
#cancatenate two vectors into a 2x2 matrix
# 0 means cat by row
torch.cat((a, b), 0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]])

In [0]:
# 1 means cat by column
torch.cat((a, b), 1)


    1     2     3     4     5     6     7     8
[torch.FloatTensor of size 1x8]

## Much more

There's definitely much more, but this was the basics about `Tensor`s fun.

*Torch* full API should be read at least once.
Hence, go [here](http://pytorch.org/docs/0.3.0/torch.html).
You'll find 100+ `Tensor` operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described.