[View in Colaboratory](https://colab.research.google.com/github/Bing5154/Summer18/blob/master/TorchPractice.ipynb)

In [0]:
# http://pytorch.org/
from os import path
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())

accelerator = 'cu90' if path.exists('/opt/bin/nvidia-smi') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.0-{platform}-linux_x86_64.whl torchvision
import torch  # <Ctrl> / <Shift> + <Return>

In [7]:
# First way, multiply using matrix and vector
# Returns 1-dimensional vector

m = torch.Tensor([[0.2, -0.5, 0.1, 2.0],
                  [1.5, 1.3, 2.1, 0.0],
                  [0.0, 0.25, 0.2, -0.3]])
v = torch.Tensor([56, 231, 24, 2])
k = torch.Tensor([1.1, 3.2, -1.2])

m @ v + k



tensor([ -96.8000,  437.9000,   60.7500])

In [8]:
# Second way, multiply using all matrices
# In order to distinguish column-wise or row-wise matrix
# Use the resize_ function

a = torch.Tensor([[0.2, -0.5, 0.1, 2.0],
                  [1.5, 1.3, 2.1, 0.0],
                  [0.0, 0.25, 0.2, -0.3]])
b = torch.Tensor([[56, 231, 24, 2]])
b. resize_(4,1)
c = torch.Tensor([[1.1, 3.2, -1.2]])
c. resize_(3,1)

a @ b + c  #highest score, classify as that object


tensor([[ -96.8000],
        [ 437.9000],
        [  60.7500]])

In [11]:
k = torch.tensor([[0.2,-0.5, 0.1, 2.0, 1.1],
                  [1.5, 1.3, 2.1, 0.0, 3.2],
                  [0.0, 0.25, 0.2, -0.3, -1.2]])
l = torch.tensor([56.0, 231.0, 24.0, 2.0, 1.0])

k @ l 


tensor([ -96.8000,  437.9000,   60.7500])

In [20]:
d = torch.tensor([1,2,3])
e = torch.tensor([1,1,1])
f = torch.tensor([[1,2],
                  [3,4]])

g = torch.tensor([[1,1],
                  [1,0]])

print("dot product: ", end= "")
d @ e
print("\nelement multiplication: ")
f * g
print("\nmatrix multiplication: ")
f @ g

dot product: 
element multiplication: 

matrix multiplication: 


tensor([[ 3,  1],
        [ 7,  3]])

In [0]:
e